open schema &myschema;


CREATE TABLE COMMUNICATION (
    COUNTRY_ID            DECIMAL(18,0),
    INTERNET_DOMAIN_CODE         VARCHAR(200) UTF8,
    INTERNET_HOSTS_NUMBER DOUBLE PRECISION,
    INTERNET_USERS_NUMBER DOUBLE PRECISION,
    LANDLINES_NUMBER      DOUBLE PRECISION,
    MOBILES_NUMBER         DOUBLE PRECISION,
    TV_CHANNELS_NUMBER     DOUBLE PRECISION
);

CREATE TABLE COUNTRY (
    COUNTRY_ID        DECIMAL(18,0),
    COUNTRY_NAME      VARCHAR(100) UTF8,
    ANTHEM_NAME       VARCHAR(2000) UTF8,
    CAPITAL_CITY      VARCHAR(2000) UTF8,
    CONTINENT_NAME         VARCHAR(2000) UTF8,
    COUNTRY_LONG_NAME VARCHAR(2000) UTF8,
    NATIONALITY_NAME       VARCHAR(2000) UTF8,
    USA_COMPARISON    VARCHAR(2000) UTF8
);

CREATE TABLE ECONOMY (
    COUNTRY_ID                       DECIMAL(18,0),
    BANK_DISCOUNT_RATE_PCT           DOUBLE PRECISION,
    BANK_LENDING_RATE_PCT            DOUBLE PRECISION,
    BROAD_MONEY_STOCK_DOLLARS        DOUBLE PRECISION,
    BUDGET_SURPLUS_PCT               DOUBLE PRECISION,
    CREIT_STOCK_DOLLARS              DOUBLE PRECISION,
    CURRENT_ACCOUNT_BALANCE_DOLLARS  DOUBLE PRECISION,
    DEBT_EXTERNAL_DOLLARS            DOUBLE PRECISION,
    DIRECT_INVESTMENT_ABROAD_DOLLARS DOUBLE PRECISION,
    DIRECT_INVESTMENT_HOME_DOLLARS   DOUBLE PRECISION,
    EDUCATION_SPEND_PCT              DOUBLE PRECISION,
    EXPORTS_DOLLARS                  DOUBLE PRECISION,
    GDP_OFFICIAL_FX_RATE_DOLLARS     DOUBLE PRECISION,
    GDP_PPP_DOLLARS                  DOUBLE PRECISION,
    HEALTH_SPEND_PCT                 DOUBLE PRECISION,
    IMPORTS_DOLLARS                  DOUBLE PRECISION,
    INCOME_DISTRIBUTION_RATIO        DOUBLE PRECISION,
    INDUSTRIAL_GROWTH_PCT            DOUBLE PRECISION,
    INFLATION_RATE_PCT               DOUBLE PRECISION,
    INVESTMENT_PCT                   DOUBLE PRECISION,
    LABOR_FORCE_NUMBER               DOUBLE PRECISION,
    MONEY_STOCK_DOLLARS              DOUBLE PRECISION,
    NARROW_MONEY_STOCK_DOLLARS       DOUBLE PRECISION,
    PERCAP_PPP_DOLLARS               DOUBLE PRECISION,
    PUBLIC_DEBT_PCT                  DOUBLE PRECISION,
    QUASI_MONEY_STOCK_DOLLARS        DOUBLE PRECISION,
    REAL_GROWTH_PCT                  DOUBLE PRECISION,
    RESERVES_GOLD_FX_DOLLARS         DOUBLE PRECISION,
    SHARES_MARKET_VALUE_DOLLARS      DOUBLE PRECISION,
    TAXES_PCT                        DOUBLE PRECISION,
    UNEMPLOYMENT_PCT                 DOUBLE PRECISION
);

CREATE TABLE HEALTH (
    COUNTRY_ID           DECIMAL(18,0),
    ADULT_OBESITY_PCT    DOUBLE PRECISION,
    HOSPITAL_BED_DENSITY DOUBLE PRECISION,
    KIDS_UNDERWEIGHT_PCT DOUBLE PRECISION,
    MATERNAL_MORTALITY_RATE   DOUBLE PRECISION,
    PHYSICIAN_DENSITY    DOUBLE PRECISION
);

CREATE TABLE MILITARY (
    COUNTRY_ID           DECIMAL(18,0),
    MALES_AVAILABLE_NUMBER      DOUBLE PRECISION,
    FEMALES_AVAILABLE_NUMBER    DOUBLE PRECISION,
    MALES_FIT_NUMBER            DOUBLE PRECISION,
    FEMALES_FIT_NUMBER          DOUBLE PRECISION,
    MALES_REACHING_AGE_NUMBER   DOUBLE PRECISION,
    FEMALES_REACHING_AGE_NUMBER DOUBLE PRECISION,
    MILITARY_SPEND_PCT   DOUBLE PRECISION
);

CREATE TABLE PHYSICAL (
    COUNTRY_ID          DECIMAL(18,0),
    TOTAL_AREA_SQ_KM    DOUBLE PRECISION,
    LAND_AREA_SQ_KM     DOUBLE PRECISION,
    WATER_AREA_SQ_KM    DOUBLE PRECISION,
    LOWEST_POINT_PLACE        VARCHAR(2000) UTF8,
    HIGHEST_POINT_PLACE       VARCHAR(2000) UTF8,
    LAND_USE_CROPS_PCT  DOUBLE PRECISION,
    LAND_USE_ARABLE_PCT DOUBLE PRECISION,
    LAND_USE_OTHER_PCT  DOUBLE PRECISION,
    COASTLINE_KM        DOUBLE PRECISION,
    IRRIGATED_SQ_KM     DOUBLE PRECISION
);

CREATE TABLE POPULATION (
    COUNTRY_ID                       DECIMAL(18,0),
    TOTAL_POPULATION                 DOUBLE PRECISION,
    BELOW_POVERTY_PCT                DOUBLE PRECISION,
    BIRTH_RATE                       DOUBLE PRECISION,
    DEATH_RATE                       DOUBLE PRECISION,
    FERTILITY                        DOUBLE PRECISION,
    HOUSEHOLD_INCOME_BOTTOM_10PC_PCT DOUBLE PRECISION,
    HOUSEHOLD_INCOME_TOP_10PC_PCT    DOUBLE PRECISION,
    POPULATION_GROWTH_PCT            DOUBLE PRECISION,
    MALE_MEDIAN_AGE_YEARS            DOUBLE PRECISION,
    FEMALE_MEDIAN_AGE_YEARS          DOUBLE PRECISION,
    TOTAL_MEDIAN_AGE_YEARS           DOUBLE PRECISION,
    NET_MIGRATION_PCT                DOUBLE PRECISION,
    URBAN_POPULATION_PCT             DOUBLE PRECISION,
    URBAN_POPULATION_GROWTH_PCT      DOUBLE PRECISION
);

CREATE TABLE TRANSPORT (
    COUNTRY_ID       DECIMAL(18,0),
    TOTAL_AIRPORTS_NUMBER   DOUBLE PRECISION,
    AIRPORTS_PAVED_NUMBER   DOUBLE PRECISION,
    AIRPORTS_UNPAVED_NUMBER DOUBLE PRECISION,
    HELIPORTS_NUMBER        DOUBLE PRECISION,
    RAILWAYS_KM         DOUBLE PRECISION,
    TOTAL_ROADWAYS_KM   DOUBLE PRECISION,
    PAVED_ROADWAYS_KM   DOUBLE PRECISION,
    UNPAVED_ROADWAYS_KM DOUBLE PRECISION
);

IMPORT INTO COMMUNICATION FROM LOCAL CSV FILE '&mydatadirectory//communication.txt' 
ENCODING = 'UTF-8' 
ROW SEPARATOR = 'LF' 
COLUMN SEPARATOR = '#' 
COLUMN DELIMITER = '"' 
SKIP = 0 
REJECT LIMIT 0;

IMPORT INTO COUNTRY FROM LOCAL CSV FILE '&mydatadirectory//country.txt' 
ENCODING = 'UTF-8' 
ROW SEPARATOR = 'LF' 
COLUMN SEPARATOR = '#' 
COLUMN DELIMITER = '"' 
SKIP = 0 
REJECT LIMIT 0;

IMPORT INTO ECONOMY FROM LOCAL CSV FILE '&mydatadirectory//economy.txt' 
ENCODING = 'UTF-8' 
ROW SEPARATOR = 'LF' 
COLUMN SEPARATOR = '#' 
COLUMN DELIMITER = '"' 
SKIP = 0 
REJECT LIMIT 0;

IMPORT INTO HEALTH FROM LOCAL CSV FILE '&mydatadirectory//health.txt' 
ENCODING = 'UTF-8' 
ROW SEPARATOR = 'LF' 
COLUMN SEPARATOR = '#' 
COLUMN DELIMITER = '"' 
SKIP = 0 
REJECT LIMIT 0;

IMPORT INTO MILITARY FROM LOCAL CSV FILE '&mydatadirectory//military.txt' 
ENCODING = 'UTF-8' 
ROW SEPARATOR = 'LF' 
COLUMN SEPARATOR = '#' 
COLUMN DELIMITER = '"' 
SKIP = 0 
REJECT LIMIT 0;

IMPORT INTO PHYSICAL FROM LOCAL CSV FILE '&mydatadirectory//physical.txt' 
ENCODING = 'UTF-8' 
ROW SEPARATOR = 'LF' 
COLUMN SEPARATOR = '#' 
COLUMN DELIMITER = '"' 
SKIP = 0 
REJECT LIMIT 0;

IMPORT INTO POPULATION FROM LOCAL CSV FILE '&mydatadirectory//population.txt' 
ENCODING = 'UTF-8' 
ROW SEPARATOR = 'LF' 
COLUMN SEPARATOR = '#' 
COLUMN DELIMITER = '"' 
SKIP = 0 
REJECT LIMIT 0;

IMPORT INTO TRANSPORT FROM LOCAL CSV FILE '&mydatadirectory//transport.txt' 
ENCODING = 'UTF-8' 
ROW SEPARATOR = 'LF' 
COLUMN SEPARATOR = '#' 
COLUMN DELIMITER = '"' 
SKIP = 0 
REJECT LIMIT 0;
